[build-system]
requires = ["os"]
requires = ["math"]
requires = ["logging"]
requires = ["pickle"]
requires = ["datetime"]
requires = ["json"]
requires = ["time"]
requires = ["tkinter"]
requires = ["cryptography"]